# Generated by Django 4.0.4 on 2023-03-06 21:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'All Groups List',
                'verbose_name_plural': 'All Groups List',
            },
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('website', models.URLField()),
                ('company_name', models.CharField(max_length=25)),
                ('business_details', models.TextField()),
                ('mail_sent', models.BooleanField(default=False)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.groups')),
            ],
            options={
                'verbose_name': 'All Users',
                'verbose_name_plural': 'All Users',
            },
        ),
        migrations.CreateModel(
            name='Excel_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_file/')),
                ('date', models.DateField(auto_now=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.groups')),
            ],
        ),
        migrations.CreateModel(
            name='EMail_container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('message', ckeditor.fields.RichTextField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.groups')),
            ],
            options={
                'verbose_name': 'Email Content',
                'verbose_name_plural': 'Email Content',
            },
        ),
    ]
