# Generated by Django 4.0.4 on 2023-02-27 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('website', models.URLField()),
                ('cname', models.CharField(max_length=25)),
                ('business_details', models.TextField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.groups')),
            ],
        ),
    ]
