# Generated by Django 4.0.4 on 2023-02-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='cname',
            new_name='company_name',
        ),
    ]
