# Generated by Django 4.0.4 on 2023-03-06 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_file',
            name='id',
        ),
        migrations.AddField(
            model_name='excel_file',
            name='gid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gid',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='mailer.excel_file'),
        ),
    ]
