# Generated by Django 4.0.4 on 2023-02-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_rename_cname_userinfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
