# Generated by Django 4.0.4 on 2023-02-27 14:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_userinfo_mail_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_file/')),
                ('date', models.DateField(auto_now=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.groups')),
            ],
        ),
        migrations.CreateModel(
            name='EMail_container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('message', ckeditor.fields.RichTextField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.groups')),
            ],
        ),
    ]
