# Generated by Django 4.0.4 on 2023-02-27 16:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_excel_file_email_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_container',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
