# Generated by Django 4.0.4 on 2023-03-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_alter_userinfo_gid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gid',
        ),
    ]
