# Generated by Django 4.0.4 on 2023-02-27 16:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_alter_email_container_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_container',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
