# Generated by Django 4.0.4 on 2023-03-06 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('website', models.URLField()),
                ('company_name', models.CharField(max_length=25)),
                ('business_details', models.TextField()),
                ('mail_sent', models.BooleanField(default=False)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.excel_file')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.groups')),
            ],
            options={
                'verbose_name': 'All Users',
                'verbose_name_plural': 'All Users',
            },
        ),
    ]
