# Generated by Django 3.2.6 on 2022-05-07 10:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mainweb.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=1000)),
                ('service', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to=mainweb.models.get_uplaod_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapBookImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=mainweb.models.get_uplaod_file)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.scrapbook')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='blog/')),
                ('discription', models.CharField(max_length=200, null=True)),
                ('writer_name', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('post_date', models.DateField()),
                ('post_now', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.category')),
                ('like_post', models.ManyToManyField(blank=True, related_name='post_like', to='mainweb.IpModel')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
