# Generated by Django 3.2.6 on 2022-05-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
