# Generated by Django 4.0.4 on 2022-05-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcribeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
