# Generated by Django 3.2.6 on 2022-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0008_auto_20220702_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbook',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
