# Generated by Django 4.0.4 on 2022-11-08 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0009_alter_scrapbook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspositions',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
