# Generated by Django 4.0.4 on 2022-11-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0010_jobspositions_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobspositions',
            old_name='expiry_date',
            new_name='expirydate',
        ),
    ]
