# Generated by Django 4.0.4 on 2023-02-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0011_rename_expiry_date_jobspositions_expirydate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Blog Comments', 'verbose_name_plural': 'Blog Comments'},
        ),
        migrations.AlterModelOptions(
            name='candidates',
            options={'verbose_name': 'Job Enquires', 'verbose_name_plural': 'job Enquires'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Category'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Forms', 'verbose_name_plural': 'Contact Forms'},
        ),
        migrations.AlterModelOptions(
            name='ipmodel',
            options={'verbose_name': 'Ip Add', 'verbose_name_plural': 'Ip Add'},
        ),
        migrations.AlterModelOptions(
            name='jobspositions',
            options={'verbose_name': 'Job Requirements', 'verbose_name_plural': 'Job Requirements'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date'], 'verbose_name': 'All Blogs', 'verbose_name_plural': 'All Blogs'},
        ),
        migrations.AlterModelOptions(
            name='subcribeusers',
            options={'verbose_name': 'Subscribed Users', 'verbose_name_plural': 'Subscribed Users'},
        ),
    ]
