# Generated by Django 4.0.4 on 2023-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0012_alter_blogcomment_options_alter_candidates_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='jobspositions',
            name='skills',
            field=models.ManyToManyField(to='mainweb.skills'),
        ),
    ]
